### ISSUE TITLE
issue building statsdaemon

### ISSUE THREAD

**Issue by gevorg15** [vimeo/statsdaemon#15]
I'm having trouble building from the master branch using go 1.5.1 on darwin and linux amd64.

No errors during the build, just no output of the binary. If I do specify a binary output, it throws an error when I try to start it up.

```
go build -a -v -o statsdaemon-amd64
runtime
sync/atomic
errors
unicode
unicode/utf8
math
sort
sync
io
syscall
github.com/tv42/topic
internal/singleflight
github.com/vimeo/statsdaemon/common
bytes
strings
time
strconv
math/rand
reflect
os
github.com/vimeo/statsdaemon/ticker
fmt
github.com/metrics20/go-metrics20
log
runtime/cgo
github.com/vimeo/statsdaemon/counters
github.com/vimeo/statsdaemon/gauges
github.com/vimeo/statsdaemon/timers
net
github.com/vimeo/statsdaemon/udp
github.com/vimeo/statsdaemon
```

Here is the output when i try to run it.
```
./statsdaemon-amd64 
./statsdaemon-amd64: line 1: syntax error near unexpected token `newline'
./statsdaemon-amd64: line 1: `!<arch>'
```

Building other apps seems to work fine.  I was able to build and use the bitly version of statsdaemon without any issues. I need the vimeo version because it has the prefix option for different metric types.

**Comment by Dieterbe** [comment]
not sure what's going on.
note that the actual program is in the statsdaemon subdirectory,
so github.com/vimeo/statsdaemon/statsdaemon.

**Comment by gevorg15** [comment]
ahh, that's exactly what it was.  Just noticed it was moved in this commit. https://github.com/vimeo/statsdaemon/commit/11faaf186a043964fae51260386dac427c3b7c50

thanks!

**Comment by Dieterbe** [comment]
just fixed the readme https://github.com/vimeo/statsdaemon/commit/88f955d68d7ca3e2f913dfbb913d89a75298e90f
