### ISSUE TITLE
Cannot build with latest go-metric20

### ISSUE THREAD

**Issue by Freeaqingme** [vimeo/statsdaemon#19]
Just attempted to build statsdaemon, but got this error:
```
GOPATH=`pwd` ~/go//bin/go get github.com/Vimeo/statsdaemon/statsdaemon
package github.com/metrics20/go-metrics20: no buildable Go source files in ~/src/statsdaemon/src/github.com/metrics20/go-metrics20
```

Checking out metrics20/go-metrics20@d9bd23f fixes it (coming from metrics20/go-metrics20@54e0842d7 ).

**Comment by Dieterbe** [comment]
I just merged https://github.com/vimeo/statsdaemon/pull/20 which should fix it

**Comment by Dieterbe** [comment]
confirmed fix

**Comment by Freeaqingme** [comment]
Tnx!
